name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "5cfd77e0e8174743bafb42876f2a1120" },
  { binding = "SHARE", id = "63a0e1987b8741b3b29239c0b2f6d9ca" }
]